### ISSUE TITLE
mandatory properties correct for Consent

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/OSLOthema-consent#25]
Hi,

In  https://purl.eu/doc/applicationprofile/consent/#Consent the application profile obliges to provide for a Consent:
 
- creation time
- is consent for data subject
- is provided by data subject
- is provided by delegation
- is provided to delegation
- is provided to controller
- location
- medium
- notice
- status

I am suprised to see that delegation is mandatory and also notice, and for medium I have no clue what is the value to provide. 
If delegation is mandatory, please a usage note with the explanation.

**Comment by michaelgeamanu** [comment]
Hi Bert,

You are right about the use of delegation. The mistake has been adapted to 0..1. Within this logic I also changed the is provided by data subject from 0..1 because - in the case of a delegation - the consent is not directly provided by the Data Subject themselves. Same for notice which is changed to 0..*. 

For Medium it is important for the completeness of the consent to always provide a Medium through which a consent was given. Possible types of mediums are indicated in an enumeration.

Best Regards,
Michael
